name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "*/5 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 365
          plugin_wakatime_sections: time, languages, languages-graph
          plugin_wakatime_limit: 5
          plugin_wakatime_url: https://waka.wabisabi.cafe
          plugin_wakatime_user: kibirisu
